#version: "3.9"

services:
  db:
    image: postgres
    environment:
     - POSTGRES_DB=tanks
     - POSTGRES_USER=tankuser
     - POSTGRES_PASSWORD=pgpwd
    volumes:
      - ./db/1.sh:/docker-entrypoint-initdb.d/1.sh
      - ./db/1.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - "5432:5432" 
  app:
   build: app/
#   stdin_open: true
#   tty: true
##   command: python -u apptank.py 
   network_mode: host
   depends_on: 
      - db